name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_square
        run: echo "::set-output name=num_squared::$(($ * $))"
        shell: bash
        env:
          GITHUB_TOKEN: $
      - name: Print the square
        run: echo "$"

